name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"

      - name: Run tests
        run: go test -v ./...

      - name: Run go vet
        run: go vet ./...

  build:
    name: Build and Release
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Build for all platforms
        run: make build-all VERSION=${{ steps.get_version.outputs.VERSION }}

      - name: Create archives
        run: |
          cd bin

          # Linux amd64
          tar -czf godo-${{ steps.get_version.outputs.VERSION }}-linux-amd64.tar.gz linux-amd64/

          # Linux arm64
          tar -czf godo-${{ steps.get_version.outputs.VERSION }}-linux-arm64.tar.gz linux-arm64/

          # macOS amd64
          tar -czf godo-${{ steps.get_version.outputs.VERSION }}-darwin-amd64.tar.gz darwin-amd64/

          # macOS arm64
          tar -czf godo-${{ steps.get_version.outputs.VERSION }}-darwin-arm64.tar.gz darwin-arm64/

          # Windows amd64
          zip -r godo-${{ steps.get_version.outputs.VERSION }}-windows-amd64.zip windows-amd64/

      - name: Generate checksums
        run: |
          cd bin
          sha256sum *.tar.gz *.zip > checksums.txt

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            bin/godo-${{ steps.get_version.outputs.VERSION }}-linux-amd64.tar.gz
            bin/godo-${{ steps.get_version.outputs.VERSION }}-linux-arm64.tar.gz
            bin/godo-${{ steps.get_version.outputs.VERSION }}-darwin-amd64.tar.gz
            bin/godo-${{ steps.get_version.outputs.VERSION }}-darwin-arm64.tar.gz
            bin/godo-${{ steps.get_version.outputs.VERSION }}-windows-amd64.zip
            bin/checksums.txt
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
